
//// TO REFACTOR !!!
export const SET_GENERAL_MESSAGE="SET_GENERAL_MESSAGE";

export const TRY_AUTH = "TRY_AUTH";

export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";

export const FETCH_BOUQUETS = "FETCH_BOUQUETS";

export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";

export const FETCH_USERS= "FETCH_USERS";

export const FETCH_SUBSCRIPTIONS='FETCH_SUBSCRIPTIONS'; 

export const SET_CUSTOMERS = "SET_CUSTOMERS";

export const SET_BOUQUETS = "SET_BOUQUETS";

export const SET_ACCOUNTS= "SET_ACCOUNTS";

export const SET_USERS= "SET_USERS";

export const CREDIT_USER= "CREDIT_USER";

export const DISCREDIT_USER= "DISCREDIT_USER";

export const SET_SUBSCRIPTIONS="SET_SUBSCRIPTIONS";

export const DEBIT_CUSTOMER_ACCOUNT= "DEBIT_CUSTOMER_ACCOUNT";

export const CREDIT_CUSTOMER_ACCOUNT= "CREDIT_CUSTOMER_ACCOUNT";

export const FREEZE_CUSTOMER_ACCOUNT="FREEZE_CUSTOMER_ACCOUNT";

export const UNFREEZE_CUSTOMER_ACCOUNT="UNFREEZE_CUSTOMER_ACCOUNT";

export const CREATE_CUSTOMER_ACCOUNT = "CREATE_CUSTOMER_ACCOUNT";

export const CREATE_USER_ACCOUNT = "CREATE_USER_ACCOUNT";

export const CUSTOMER_ACCOUNT_CREATED="CUSTOMER_ACCOUNT_CREATED";

export const CUSTOMER_ACCOUNT_UPDATED="CUSTOMER_ACCOUNT_UPDATED";

export const SET_CONNECTED_USER = "SET_CONNECTED_USER";

export const SET_REQUIRE_USER_CREDENTIALS = "REQUIRE_USER_CREDENTIALS";

export const SET_CURRENT_AGENCY="SET_CURRENT_AGENCY";

export const SET_SUBSCRIPTION_ONGOING="SET_SUBSCRIPTION_ONGOING";

export const SET_SUBSCRIPTION_ABORTED="SET_SUBSCRIPTION_ABORTED";

export const SET_SUBSCRIPTION_DONE="SET_SUBSCRIPTION_DONE";

export const DISCONNECT_USER="DISCONNECT_USER";

export const USER_DISCONNECTED="USER_DISCONNECTED";

export const FILTER_SUBSCRIPTIONS="FILTER_SUBSCRIPTIONS";

export const SUBS_FILTER = {
    NONE:"NONE",
    CONFIRMED:"CONFIRMED",
    WAITING:"WAITING",
    CANCELLED:"CANCELLED",
    ONGOING:"ONGOING"
}