
export const SEARCH_BOUQUET="SEARCH_BOUQUET";
export const SEARCH_ACCOUNT="SEARCH_ACCOUNT";
export const SEARCH_SUB = "SEARCH_SUB";
export const SEARCH_USER = "SEARCH_USER";

//// TO REFACTOR LATER !!!
export const SET_GENERAL_MESSAGE="SET_GENERAL_MESSAGE";

export const SET_CUSTOMERS = "SET_CUSTOMERS";

export const SET_BOUQUETS = "SET_BOUQUETS";

export const SET_ACCOUNTS= "SET_ACCOUNTS";

export const SET_AGENCY_ACCOUNT = "SET_AGENCY_ACCOUNT";

export const SET_AGENCY_ACCOUNT_ACTIVITY =  "SET_SGENCY_ACCOUNT_ACTIVITY";

export const SET_USERS= "SET_USERS";

export const SET_SUBSCRIPTIONS="SET_SUBSCRIPTIONS";

export const SET_CONNECTED_USER = "SET_CONNECTED_USER";

export const SET_REQUIRE_USER_CREDENTIALS = "REQUIRE_USER_CREDENTIALS";

export const SET_CURRENT_AGENCY="SET_CURRENT_AGENCY";

export const FILTER_SUBSCRIPTIONS="FILTER_SUBSCRIPTIONS";

export const SUBS_FILTER = {
    NONE:"NONE",
    CONFIRMED:"CONFIRMED",
    WAITING:"WAITING",
    CANCELLED:"CANCELLED",
    ONGOING:"ONGOING"
}

export const BOUQUETS_FILTER = {
    NONE:'NONE',
    PRICE:'PRICE'
}